# Generated by Django 5.1.3 on 2024-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_Img', models.ImageField(upload_to='./api/media/images/logo')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
