# Generated by Django 5.1.3 on 2024-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./api/media/images/local')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
