# Generated by Django 5.1.3 on 2025-01-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('What_We_Do', models.TextField(blank=True)),
                ('Core_values', models.TextField(blank=True)),
                ('Call_for_action', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donation_ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('volunteer_name', models.CharField(blank=True, max_length=255)),
                ('volunteer_email', models.EmailField(max_length=254)),
                ('volunteer_hours', models.IntegerField(blank=True)),
                ('advocate_name', models.CharField(blank=True, max_length=255)),
                ('advocate_email', models.EmailField(max_length=254)),
                ('advocacy_message', models.TextField(blank=True)),
                ('gift_name', models.CharField(blank=True, max_length=255)),
                ('gift_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('gift_description', models.TextField(blank=True)),
                ('fundraiser_name', models.CharField(blank=True, max_length=255)),
                ('fundraiser_email', models.EmailField(max_length=254)),
                ('fundraised_ammount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='./api/media/images/events')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('ngo', 'NGO'), ('corporation', 'Corporation'), ('government', 'Government Agency'), ('individual', 'Individual')], max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(help_text='can be image or logo of the partner', upload_to='./api/media/images/partners')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
