# Generated by Django 5.1.6 on 2025-02-17 14:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_Img', models.ImageField(blank=True, null=True, upload_to='./api/media/images/logo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, help_text='safari question', max_length=255, null=True)),
                ('answer', models.TextField(blank=True, help_text='safari answer', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafariPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of the safari place', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./api/media/images/safaris/Places')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('county', models.CharField(blank=True, help_text='local county of the safari place', max_length=150, null=True)),
                ('rating', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('areas_To_Visit', models.TextField(blank=True, help_text='the areas in the safari to be visited', null=True)),
                ('safari_Type', models.CharField(blank=True, help_text='type of the safari place', max_length=255, null=True)),
                ('is_Favourite', models.ManyToManyField(blank=True, null=True, related_name='favourite_safari_places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
