# Generated by Django 5.1.6 on 2025-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safariplace',
            old_name='areas_To_Visit',
            new_name='areas_to_visit',
        ),
        migrations.RenameField(
            model_name='safariplace',
            old_name='safari_Type',
            new_name='safari_type',
        ),
        migrations.RemoveField(
            model_name='safariplace',
            name='is_Favourite',
        ),
        migrations.AddField(
            model_name='safariplace',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
