# Generated by Django 5.1.6 on 2025-02-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_safariplace_safari_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safariplace',
            name='price',
            field=models.DecimalField(blank=True, choices=[('15', '15,000'), ('18', '18,000'), ('20', '20,000'), ('23', '23,000'), ('25', '25,000'), ('27', '27,000'), ('30', '30,000')], decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='safariplace',
            name='rating',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, null=True),
        ),
    ]
