# Generated by Django 5.1.6 on 2025-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_safariplace_price_alter_safariplace_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safariplace',
            name='price',
            field=models.DecimalField(blank=True, choices=[('15', '15000'), ('18', '18000'), ('20', '20000'), ('23', '23000'), ('25', '25000'), ('27', '27000'), ('30', '30000')], decimal_places=2, max_digits=10, null=True),
        ),
    ]
