# Generated by Django 5.1.6 on 2025-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_safariplace_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safariplace',
            name='price',
            field=models.DecimalField(blank=True, choices=[('15000', '15,000'), ('18000', '18,000'), ('20000', '20,000'), ('23000', '23,000'), ('25000', '25,000'), ('27000', '27,000'), ('30000', '30,000')], decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='safariplace',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
    ]
