# Generated by Django 5.1.6 on 2025-02-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_safariplace_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safariplace',
            name='price',
            field=models.IntegerField(blank=True, choices=[('15,000', 15000), ('18,000', 18000), ('20,000', 20000), ('23,000', 23000), ('25,000', 25000), ('27,000', 27000), ('30,000', 30000)], null=True),
        ),
    ]
