# Generated by Django 5.1.6 on 2025-02-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_safariplace_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safariplace',
            name='days',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], help_text='number of days of the tour', null=True),
        ),
    ]
