# Generated by Django 5.1.6 on 2025-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_safariplace_comfort_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safariplace',
            name='price',
            field=models.IntegerField(blank=True, choices=[(500, '500'), (750, '750'), (1000, '1,000'), (1250, '1,250'), (1500, '1,500'), (1750, '1,750'), (2000, '2,000'), (2250, '2,250'), (2500, '2,500'), (2750, '2,750'), (3000, '3,000')], null=True),
        ),
    ]
